#Descargar Ubuntu 20.04
FROM ubuntu:20.04

#Etiquetas sobre el autor
LABEL description = "Imagen, trabajar con Ubuntu, Python y Pytest en un contenedor"
LABEL mainteiner = "Janeth Atenco Franco"
LABEL version = "0.1"

#Actualizar Ubuntu
RUN apt update
RUN apt install -y python3
RUN apt install -y python3-pip
RUN pip install pytest